[2024-01-18T22:17:44.045+0300] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: Google_X_mention_score.get_data scheduled__2024-01-01T06:30:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-01-18T22:17:44.052+0300] {local_task_job.py:151} INFO - Task is not able to be run
