[2024-01-18T21:37:03.358+0300] {processor.py:153} INFO - Started process (PID=3312) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:37:03.360+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:37:03.363+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:37:03.362+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:37:03.441+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:37:03.431+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:37:03.442+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:37:03.442+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:37:03.442+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:37:03.478+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.161 seconds
[2024-01-18T21:38:01.475+0300] {processor.py:153} INFO - Started process (PID=3434) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:38:01.477+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:38:01.478+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:38:01.478+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:38:01.585+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:38:01.584+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:38:01.586+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:38:01.585+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:38:01.586+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:38:01.639+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.172 seconds
[2024-01-18T21:39:16.735+0300] {processor.py:153} INFO - Started process (PID=4140) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:39:16.738+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:39:16.739+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:39:16.739+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:39:16.777+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:39:16.776+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:39:16.778+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:39:16.778+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:39:16.778+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:39:16.799+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2024-01-18T21:40:16.011+0300] {processor.py:153} INFO - Started process (PID=4202) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:40:16.014+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:40:16.016+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:40:16.015+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:40:16.055+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:40:16.054+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:40:16.056+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:40:16.056+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:40:16.057+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:40:16.081+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2024-01-18T21:41:22.806+0300] {processor.py:153} INFO - Started process (PID=4312) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:41:22.814+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:41:22.816+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:41:22.816+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:41:22.876+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:41:22.875+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:41:22.876+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:41:22.876+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:41:22.877+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:41:22.906+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.113 seconds
[2024-01-18T21:42:21.020+0300] {processor.py:153} INFO - Started process (PID=4373) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:42:21.023+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:42:21.025+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:42:21.024+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:42:21.277+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:42:21.276+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:42:21.277+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:42:21.277+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:42:21.277+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:42:21.292+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.280 seconds
[2024-01-18T21:43:16.126+0300] {processor.py:153} INFO - Started process (PID=4425) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:43:16.129+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:43:16.130+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:43:16.130+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:43:16.168+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:43:16.166+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:43:16.168+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:43:16.168+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:43:16.168+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:43:16.186+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-01-18T21:44:05.147+0300] {processor.py:153} INFO - Started process (PID=4478) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:44:05.150+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:44:05.151+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:44:05.151+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:44:05.198+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:44:05.197+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:44:05.199+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:44:05.198+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:44:05.199+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:44:05.218+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2024-01-18T21:44:55.387+0300] {processor.py:153} INFO - Started process (PID=4537) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:44:55.389+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:44:55.390+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:44:55.390+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:44:55.437+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:44:55.436+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:44:55.437+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:44:55.437+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:44:55.438+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:44:55.467+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2024-01-18T21:45:46.803+0300] {processor.py:153} INFO - Started process (PID=4618) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:45:46.806+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:45:46.807+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:45:46.807+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:45:46.845+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:45:46.844+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:45:46.846+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:45:46.846+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:45:46.846+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:45:46.865+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2024-01-18T21:46:36.056+0300] {processor.py:153} INFO - Started process (PID=4689) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:46:36.059+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:46:36.060+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:46:36.060+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:46:36.100+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:46:36.099+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:46:36.100+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:46:36.100+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:46:36.101+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:46:36.140+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2024-01-18T21:47:25.108+0300] {processor.py:153} INFO - Started process (PID=4747) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:47:25.110+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:47:25.112+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:47:25.111+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:47:25.149+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:47:25.148+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:47:25.149+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:47:25.149+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:47:25.150+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:47:25.169+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2024-01-18T21:48:15.048+0300] {processor.py:153} INFO - Started process (PID=4819) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:48:15.050+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:48:15.052+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:48:15.051+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:48:15.090+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:48:15.089+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:48:15.091+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:48:15.090+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:48:15.091+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:48:15.111+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-01-18T21:49:09.007+0300] {processor.py:153} INFO - Started process (PID=4872) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:49:09.010+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:49:09.013+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:49:09.013+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:49:09.048+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:49:09.047+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:49:09.049+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:49:09.049+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:49:09.049+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:49:09.067+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-01-18T21:49:57.863+0300] {processor.py:153} INFO - Started process (PID=4919) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:49:57.866+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:49:57.868+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:49:57.867+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:49:57.906+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:49:57.904+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:49:57.906+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:49:57.906+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:49:57.907+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:49:57.927+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-01-18T21:50:49.007+0300] {processor.py:153} INFO - Started process (PID=4968) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:50:49.010+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:50:49.011+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:50:49.011+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:50:49.050+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:50:49.048+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:50:49.050+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:50:49.050+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:50:49.051+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:50:49.069+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2024-01-18T21:51:40.685+0300] {processor.py:153} INFO - Started process (PID=5017) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:51:40.688+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:51:40.689+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:51:40.689+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:51:40.727+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:51:40.726+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:51:40.728+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:51:40.727+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:51:40.728+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:51:40.748+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2024-01-18T21:52:36.539+0300] {processor.py:153} INFO - Started process (PID=5070) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:52:36.542+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:52:36.544+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:52:36.543+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:52:36.627+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:52:36.625+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:52:36.628+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:52:36.627+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:52:36.630+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:52:36.654+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.131 seconds
[2024-01-18T21:53:33.863+0300] {processor.py:153} INFO - Started process (PID=5126) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:53:33.870+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T21:53:33.874+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:53:33.873+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:53:33.945+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:53:33.943+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T21:53:33.946+0300] {logging_mixin.py:137} INFO - [2024-01-18T21:53:33.946+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T21:53:33.947+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T21:53:33.991+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.144 seconds
[2024-01-18T22:00:44.814+0300] {processor.py:153} INFO - Started process (PID=5513) to work on /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T22:00:44.818+0300] {processor.py:743} INFO - Processing file /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-18T22:00:44.820+0300] {logging_mixin.py:137} INFO - [2024-01-18T22:00:44.819+0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T22:00:44.890+0300] {logging_mixin.py:137} INFO - [2024-01-18T22:00:44.888+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-18T22:00:44.891+0300] {logging_mixin.py:137} INFO - [2024-01-18T22:00:44.890+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-18T22:00:44.891+0300] {processor.py:755} WARNING - No viable dags retrieved from /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-18T22:00:44.927+0300] {processor.py:175} INFO - Processing /home/angry/mlops_4/venv4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.134 seconds
